### ISSUE TITLE
Twitter References

### ISSUE THREAD

**Issue by makalaaneesh** [dvargas92495/roam-js-extensions#64]
Hi @dvargas92495 ,

I thought it'd be cool if we could pull tweet references from twitter into Roam! So, for instance, if you find something interesting on twitter, you can quote tweet it with a `[[xyz]]`, and on Roam, you can pull that data using the twitter search API. I managed to pull off a prototype. (find the GIF below).

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6829754/93001556-6ee4d980-f54d-11ea-9002-9c95284b0bc6.gif)

Few questions/issues:
1. Twitter doesn't allow CORS, so we can't take the token from the user and make the request. For now, I just created a proxy server locally which hits twitter and passes the response back to the browser. Anyway, tweets are mostly public, so shouldn't be a problem. This can be implemented in the same way that you've implemented the google-calendar (using a lambda).
2. After running, the browser tab gets stuck for some reason. I've reused `pushBullets` but there seems to be some issue. The entire tab becomes unresponsive, and I have to reload Roam. After I reload, i see some waitingForTyping error with a bunch of html and css in that block. Very strange. 
3. How do I pull the current page title? Right now, I've hardcoded the search query.
3. One caveat with this is that the standard twitter search API allows only searching for the last 7 days of tweets. So, this is a bit limiting, but as a workflow, I guess some people would be ok with pulling only their tweets into roam on a daily/weekly basis.

Future thoughts:
1. We could parameterize the search like `{{twitter references from:@naval text:money}}` 
2. Historical tweet search with count. How do we do this without having to setup an enterprise account on twitter. [loklak](https://loklak.org/) is promising, but it's not working for some reason.

**Comment by dvargas92495** [comment]
Ah! so is this to reference a set of tweets instead of just one like below?
![image](https://user-images.githubusercontent.com/7143571/93004838-f6fcbc00-f518-11ea-94e3-b46091f8f798.png)

We could also parameterize to import as a link or as a text

1. Yea I would see us using Lambda for an API token, just like google-cal/github
2. `pushBullets` uses a `waitFor` function to verify that the typed in string matches what's in the text area. This is bc there were race conditions between separate `type` calls. We should probably add a timeout or handle the failure case better. If it fails, it's probably because the text has periods and it's related to https://github.com/dvargas92495/roam-js-extensions/issues/47
3. I would just query the DOM, `document.getElementsByClassName("rm-title-display")[0]`
4. Yea I would think more about what do users want to query? Thinking through my potential use cases, I'd only want to import my likes from the last 7 days for example.

1. I would advise getting an MVP out, and letting users inform how to parameterize instead of overparameterizing (a mistake I think I made with the github integration)
2. There might be APIs out there that read the twitter feed and store it elsewhere for querying. I'm not personally familiar with any

**Comment by makalaaneesh** [comment]
> Ah! so is this to reference a set of tweets instead of just one like below?

Well not really. My intention was that on a given roam page, currently, we see linked references and unlinked references. In addition, what if we could see twitter references of that page made by us. 

So, for example - since you tweet a lot about roam research, if you head over to [[roam research]] on your roam app and click on `{{twitter references}}`, you will get a list of all the tweets made by you containing the keywords `roam research`.

> pushBullets uses a waitFor function to verify that the typed in string matches what's in the text area. This is bc there were race conditions between separate type calls. We should probably add a timeout or handle the failure case better. If it fails, it's probably because the text has periods and it's related to #47

You're right. I think it does relate to the period issue. I tried logging instead of throwing an error if the text area doesn't match the input string, but that's delaying the enters, and so all the bullets end up on one bullet. I don't really understand the javascript event loop quite well, so I'm sure i'm missing something! 😅

**Comment by dvargas92495** [comment]
oh! that's dope I misunderstood what you meant by references, it's the literal Roam definition. I like it!

Yea this period issue sucks and can't figure out what's going on. we could make the check more graceful such that we don't need strict equality, but just the lengths of the two string to be within 10% of each other or something like that

We throw the error based on how `waitFor` works from `userEvent`, which basically waits until no error is thrown

**Comment by makalaaneesh** [comment]
Alright, so I relaxed the check to ignore if periods were missing. (doesn't solve the actual problem but atleast it lets me type stuff). Hyperlinks is still a big issue though. If we solve that, I can just paste the tweet link, so it will get rendered properly (like in the image you shared above)

Here's how it will look! You can go to the page `[[roam]]` and you get all the tweets where you mentioned roam on twitter, right into that roam page!
![rt2](https://user-images.githubusercontent.com/6829754/93013072-c4a79900-f5c2-11ea-8b81-395848c7a773.gif)

**Comment by makalaaneesh** [comment]
Ok, strange observation. The period issue only happens for the first bullet. 

Here, I just pushed the URL of each tweet into each bullet.

![rt3](https://user-images.githubusercontent.com/6829754/93013493-9cba3480-f5c6-11ea-80ad-e9ac810427fb.gif)

**Comment by makalaaneesh** [comment]
Created https://github.com/dvargas92495/roam-js-extensions/pull/65/ for the temporary fix

**Comment by dvargas92495** [comment]
This integration is awesome!

The period issue astounds me to no end. It looks like it happens for the first bullet that has a period? meaning if you have three non period bullets, then a period bullet, that fourth one hits the bug right?

Crazy stuff

**Comment by makalaaneesh** [comment]
Closed by https://github.com/dvargas92495/roam-js-extensions/pull/66
