### ISSUE TITLE
Wiki data -- misleading name

### ISSUE THREAD

**Issue by kvistgaard** [dvargas92495/roam-js-extensions#646]
Please consider changing the name not to imply that the data is pulled from Wikidata.
Although both Wikipedia and Wikidata are both Wikimedia Foundation projects, they are fundamentally different in content and in the way they manage and serve information.
And by the way, a Wikidata Roam extension is much needed.

**Comment by dvargas92495** [comment]
I'm hesitant to change the name because the extension currently sees 600-800 downloads per day. Changing the name would break it for those users. So safely cutting over to a new name would take more effort than is probably worth.

I would rather build wiki data functionality bundled with this extension
